### ISSUE TITLE
模拟器上无法播放

### ISSUE THREAD

**Issue by Fixfly-SS** [karelrooted/MPVKitExample#1]
你好,打扰了, 我在模拟器上运行这个例子,无法播放视频,  真机运行可以
下面是日志信息

[   1.470][v][cplayer] Opening done: https://streams.videolan.org/streams/mp4/Mr_MrsSmith-h264_aac.mp4
[   1.553][v][cplayer] Running hook: ytdl_hook/on_preloaded
[   1.553][v][lavf] select track 0
[   1.553][v][lavf] select track 1
[   1.553][i][cplayer]  (+) Video --vid=1 (*) (h264 320x176 25.000fps)
[   1.553][i][cplayer]  (+) Audio --aid=1 --alang=eng (*) (aac 2ch 44100Hz)
[   1.555][v][vo/gpu-next] Probing for best GPU context.
[   1.555][e][vo/gpu-next] Failed initializing any suitable GPU context!
[   1.557][f][cplayer] Error opening/initializing the selected video_out (--vo) device.
[   1.557][v][lavf] deselect track 0
[   1.557][i][cplayer] Video: no video
[   1.559][v][ad] Codec list:
[   1.559][v][ad]     aac - AAC (Advanced Audio Coding)
[   1.559][v][ad]     aac_fixed (aac) - AAC (Advanced Audio Coding)
[   1.559][v][ad]     aac_at (aac) - aac (AudioToolbox)
[   1.559][v][ad] Opening decoder aac
[   1.559][v][ad] Requesting 1 threads for decoding.
[   1.568][v][ad] Selected codec: AAC (Advanced Audio Coding)
[   1.568][v][af] User filter list:
[   1.568][v][af]   (empty)
[   1.568][v][cplayer] Starting playback...
[   1.568][v][cplayer] EOF code: 6  
[   1.568][d][ad] Uninit decoder.
[   1.569][d][cplayer] Terminating demuxers...
[   1.569][d][ffmpeg] AVIOContext: Statistics: 32412 bytes read, 0 seeks
[   1.570][d][cplayer] Done terminating demuxers.
[   1.570][v][cplayer] finished playback, something happened (reason 4)
[   1.573][v][cplayer] Set property: pause=true -> 1
[   1.573][d][cplayer] Run command: stop, flags=64, args=[flags=""]

**Comment by karelrooted** [comment]
模拟器还真没调试过，可能vo=gpu-next真的没法运行（gpunext是一个临时测试的方案，patch也是被官方close掉的pr，不过我本地播了一段时间，倒是没有大的问题），估计得用vo=libmpv，用opengl运行，不过代码会比较怪，模拟器走opengl，真机走libplacebo， mpvkit代码之前被我rebase了，opengl的例子没了，可以参考一下yattee或者mpv team成员的例子

**Comment by Fixfly-SS** [comment]
> 模拟器还真没调试过，可能vo=gpu-next真的没法运行（gpunext是一个临时测试的方案，patch也是被官方close掉的pr，不过我本地播了一段时间，倒是没有大的问题），估计得用vo=libmpv，用opengl运行，不过代码会比较怪，模拟器走opengl，真机走libplacebo， mpvkit代码之前被我rebase了，opengl的例子没了，可以参考一下yattee或者mpv team成员的例子

嗯 我现在就是模拟器用opengl 真机用metal， 之前 https://github.com/cxfksword/MPVKit  用这个库的0.36.0 版本   ，opengl 会导致上层UI动画卡顿掉帧（播放本身没问题）， 现在0.37 版本 好像卡顿更严重了 （也很大可能是我swift UI写的有问题）
